name = "codecrafters_redis"
version = "0.6.0"

[dependencies]
gleam_stdlib = ">= 0.43.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
glisten = ">= 6.0.0 and < 7.0.0"
snag = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
